from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.ollama_ocr_extract import clean_ollama_output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rewrite an existing Ollama OCR CSV by cleaning the extracted text column."
    )
    parser.add_argument(
        "--input-csv",
        required=True,
        help="Source CSV generated by ollama_ocr_extract.py.",
    )
    parser.add_argument(
        "--output-csv",
        required=True,
        help="Destination CSV for cleaned rows.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_csv = Path(args.output_csv)

    if not input_csv.exists():
        raise FileNotFoundError(f"Missing input CSV: {input_csv}")

    with input_csv.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = list(reader.fieldnames or ["path", "model", "text", "error"])
        rows = list(reader)

    cleaned_rows = []
    changed_count = 0
    for row in rows:
        row = dict(row)
        original_text = str(row.get("text") or "")
        if not str(row.get("error") or "").strip():
            cleaned_text = clean_ollama_output(original_text)
            if cleaned_text != original_text:
                changed_count += 1
            row["text"] = cleaned_text
        cleaned_rows.append(row)

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(cleaned_rows)

    print(f"Rows read: {len(rows)}")
    print(f"Rows changed: {changed_count}")
    print(f"Saved cleaned CSV to: {output_csv.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
