from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Deduplicate an Ollama OCR CSV by keeping the best row per image path. "
            "A successful row is preferred over an error row; among rows of the same kind, the latest row wins."
        )
    )
    parser.add_argument(
        "--input-csv",
        required=True,
        help="Path to the source CSV generated by ollama_ocr_extract.py.",
    )
    parser.add_argument(
        "--output-csv",
        required=True,
        help="Path to the deduplicated output CSV.",
    )
    return parser.parse_args()


def row_priority(index: int, row: dict[str, str]) -> tuple[int, int]:
    has_success = 1 if not str(row.get("error") or "").strip() else 0
    return (has_success, index)


def main() -> int:
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_csv = Path(args.output_csv)

    if not input_csv.exists():
        raise FileNotFoundError(f"Missing input CSV: {input_csv}")

    with input_csv.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = list(reader.fieldnames or ["path", "model", "text", "error"])
        best_rows: dict[str, tuple[tuple[int, int], dict[str, str]]] = {}
        source_rows = 0

        for index, row in enumerate(reader):
            source_rows += 1
            image_path = str(row.get("path") or "").strip()
            if not image_path:
                continue

            priority = row_priority(index, row)
            previous = best_rows.get(image_path)
            if previous is None or priority > previous[0]:
                best_rows[image_path] = (priority, row)

    deduped_rows = [item[1] for item in best_rows.values()]
    deduped_rows.sort(key=lambda row: str(row.get("path") or ""))

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(deduped_rows)

    success_count = sum(1 for row in deduped_rows if not str(row.get("error") or "").strip())
    error_count = len(deduped_rows) - success_count

    print(f"Source rows: {source_rows}")
    print(f"Unique image paths: {len(deduped_rows)}")
    print(f"Successful rows kept: {success_count}")
    print(f"Errored rows kept: {error_count}")
    print(f"Saved deduplicated CSV to: {output_csv.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
